networks:
    default:
        driver: bridge

volumes:
    mysql_data:
        driver: local
    node_modules:
        driver: local

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx.dockerfile
        image: 767398029156.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
        container_name: php_nginx
        restart: unless-stopped
        networks:
            - default
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8000:80'
        depends_on:
            - laravel
            - mysql

    laravel:
        build:
            context: .
            dockerfile: docker/laravel.dockerfile
        image: 767398029156.dkr.ecr.us-east-1.amazonaws.com/laravel:latest
        container_name: laravel_php
        restart: unless-stopped
        networks:
            - default
        environment:
            APP_ENV: local
            APP_DEBUG: true
            DB_HOST: mysql
            DB_DATABASE: tasks
            DB_USERNAME: root
            DB_PASSWORD: password123
            DB_PORT: 3306
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        command: /bin/sh -c "php artisan migrate --force && php-fpm"

    mysql:
        image: mysql:8.4
        container_name: mysql_db
        restart: unless-stopped
        command: --mysql-native-password=ON
        environment:
            MYSQL_ROOT_PASSWORD: password123
            MYSQL_DATABASE: tasks
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - 3307:3306
        networks:
            - default
        healthcheck:
            test: ['CMD', 'ping', '-h', 'localhost']
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 60s

    vite:
        build:
            context: .
            dockerfile: docker/vite.dockerfile
        image: 767398029156.dkr.ecr.us-east-1.amazonaws.com/vite:latest
        container_name: vite_dev_server
        working_dir: /var/www/html
        command: npm run dev
        ports:
            - '5173:5173'
        volumes:
            - .:/var/www/html
            - node_modules:/var/www/html/node_modules
        networks:
            - default
        depends_on:
            - laravel
