# docker-compose.yml
version: '3.8'

services:
  # Laravel/PHP with SSR support for Vite (React in resources/js)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=password
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db

  # MySQL database container
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  # Nginx container for Laravel
  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - app

volumes:
  mysql_data:
